version: "3"

services:
  web:
    build: .
    volumes:
      - .:/home/winner/myapp
      - bundle_path:/home/winner/bundle
    environment:
      - BUNDLE_PATH=/home/winner/bundle/vendor
      - BUNDLE_APP_CONFIG=/home/winner/myapp/.bundle
    user: winner
    command:
      - bundle
      - exec
      - rails
      - server
      - --binding=0.0.0.0
      - --port=3000
    ports:
      - "3000:3000"

volumes:
  bundle_path:
