version: "3"

services:
  web:
    build: .
    volumes:
      - .:/home/winner/myapp
      - bundle_path:/home/winner/bundle
    environment:
      - BUNDLE_PATH=/home/winner/bundle/vendor
      - BUNDLE_APP_CONFIG=/home/winner/myapp/.bundle
    user: winner
    command: bin/server
    ports:
      - "4000:4000"

volumes:
  bundle_path:
